//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlassian.plvs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlassian.plvs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;text-align:center;font-size:10px;font-family:Arial;&quot;&gt;
        ///
        ///The Atlassian Connector for Microsoft Visual Studio is an Visual Studio package that lets you work&lt;br&gt;
        ///with the Atlassian products within your IDE. Now you don&apos;t have to switch between websites,&lt;br&gt;
        ///email messages and news feeds to see what&apos;s happening to your project and your code.&lt;br&gt;
        ///Instead, you can see the relevant &lt;a href=&quot;http://www.atlassian.com/software/jira/&quot;&gt;JIRA&lt;/a&gt; issues
        ///and &lt;a href=&quot;http://www.atlassian.com/software/bamb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about_html {
            get {
                return ResourceManager.GetString("about_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add_jira {
            get {
                object obj = ResourceManager.GetObject("add_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Atlassian {
            get {
                object obj = ResourceManager.GetObject("Atlassian", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap atlassian_538x235 {
            get {
                object obj = ResourceManager.GetObject("atlassian_538x235", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap atlassian_installer {
            get {
                object obj = ResourceManager.GetObject("atlassian_installer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;padding:2em;margin:0;&quot;&gt;
        ///&lt;div style=&quot;font-family:{0};font-size:12px;&quot;&gt;
        ///
        ///&lt;center&gt;Unable to view attachment {1}&lt;/center&gt;
        ///&lt;center&gt;Right-click on it and select &quot;Save as...&quot; from the menu to save attachment as a file&lt;/center&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///.
        /// </summary>
        internal static string attachment_download_html {
            get {
                return ResourceManager.GetString("attachment_download_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;padding:0;margin:0;background-color:{1};&quot;&gt;
        ///&lt;div style=&quot;font-family:{0};font-size:12px;background-color:{1};&quot;&gt;
        ///
        ///&lt;div&gt;New Version of the connector is available: &lt;strong&gt;{2}&lt;/strong&gt;&lt;/div&gt;
        ///&lt;br&gt;
        ///&lt;div style=&quot;font-size:large;&quot;&gt;Highlights of the new version:&lt;/div&gt;
        ///
        ///&lt;div&gt;{3}&lt;/div&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///.
        /// </summary>
        internal static string autoupdate_html {
            get {
                return ResourceManager.GetString("autoupdate_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bamboo_blue_16 {
            get {
                object obj = ResourceManager.GetObject("bamboo_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bamboo_blue_16_with_padding {
            get {
                object obj = ResourceManager.GetObject("bamboo_blue_16_with_padding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bamboo_green_16 {
            get {
                object obj = ResourceManager.GetObject("bamboo_green_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bamboo_green_161 {
            get {
                object obj = ResourceManager.GetObject("bamboo_green_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bamboo_grey_16 {
            get {
                object obj = ResourceManager.GetObject("bamboo_grey_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bamboo_grey_161 {
            get {
                object obj = ResourceManager.GetObject("bamboo_grey_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bamboo_red_16 {
            get {
                object obj = ResourceManager.GetObject("bamboo_red_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon bamboo_red_161 {
            get {
                object obj = ResourceManager.GetObject("bamboo_red_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bluetick {
            get {
                object obj = ResourceManager.GetObject("bluetick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;summary&quot;&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Build Number&lt;/td&gt;&lt;td&gt;{0}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Build State&lt;/td&gt;&lt;td style=&quot;color:{8};&quot;&gt;{7}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Build Key&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Build Reason&lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Tests&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Completed&lt;/td&gt;&lt;td&gt;{4}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Duration&lt;/td&gt;&lt;td&gt;{5}&lt;/td&gt;&lt;/tr&gt;
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Server&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string build_summary_html {
            get {
                return ResourceManager.GetString("build_summary_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builds - Bamboo.
        /// </summary>
        internal static string BuildDetailsToolWindowTitle {
            get {
                return ResourceManager.GetString("BuildDetailsToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close {
            get {
                object obj = ResourceManager.GetObject("close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse_all {
            get {
                object obj = ResourceManager.GetObject("collapse_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///.comment_header{
        ///	background: lightgrey;
        ///	width: 100%;
        ///	height: 1em;
        ///	padding: 0.2em 0.5em;
        ///	border-bottom: 1px dotted;
        ///	font-family: Arial;
        ///	font-size: 10pt;
        ///}
        ///
        ///.author {
        ///	position: relative;
        ///	float: left;
        ///	left: 1em;
        ///	font-weight: bold;
        ///}
        ///
        ///.date {
        ///	font-style: italic;
        ///	font-weight: normal;
        ///}
        ///
        ///.toggler {
        ///	position: relative;
        ///	float: right;
        ///	right: 1em;
        ///	cursor:pointer;
        ///}
        ///
        ///.comment_body {
        ///	background: white;
        ///	width: 100%;
        ///	font-family: Arial;
        ///	font-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string comments_css {
            get {
                return ResourceManager.GetString("comments_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dropzone {
            get {
                object obj = ResourceManager.GetObject("dropzone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand_all {
            get {
                object obj = ResourceManager.GetObject("expand_all", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body style=&quot;padding:2em;margin:0;&quot;&gt;
        ///&lt;div style=&quot;font-family:{0};font-size:12px;&quot;&gt;
        ///
        ///&lt;center&gt;Unable to explore JIRA server {1}&lt;/center&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string explorer_navigator_error_html {
            get {
                return ResourceManager.GetString("explorer_navigator_error_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_bamboo {
            get {
                object obj = ResourceManager.GetObject("find_bamboo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_jira {
            get {
                object obj = ResourceManager.GetObject("find_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_bamboo {
            get {
                object obj = ResourceManager.GetObject("folder_bamboo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_jira {
            get {
                object obj = ResourceManager.GetObject("folder_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap global_properties {
            get {
                object obj = ResourceManager.GetObject("global_properties", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icn_comment {
            get {
                object obj = ResourceManager.GetObject("icn_comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icn_label {
            get {
                object obj = ResourceManager.GetObject("icn_label", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icn_plan_disabled {
            get {
                object obj = ResourceManager.GetObject("icn_plan_disabled", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icn_plan_failed {
            get {
                object obj = ResourceManager.GetObject("icn_plan_failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icn_plan_passed {
            get {
                object obj = ResourceManager.GetObject("icn_plan_passed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_activateissue {
            get {
                object obj = ResourceManager.GetObject("ico_activateissue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_clonefilter {
            get {
                object obj = ResourceManager.GetObject("ico_clonefilter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_copytoclipboard {
            get {
                object obj = ResourceManager.GetObject("ico_copytoclipboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_editinbrowser {
            get {
                object obj = ResourceManager.GetObject("ico_editinbrowser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_editinide {
            get {
                object obj = ResourceManager.GetObject("ico_editinide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_groupsubtasks {
            get {
                object obj = ResourceManager.GetObject("ico_groupsubtasks", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_inactiveissue {
            get {
                object obj = ResourceManager.GetObject("ico_inactiveissue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_jira_custom_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_custom_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_jira_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_jira_preset_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_preset_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_jira_recent_issues {
            get {
                object obj = ResourceManager.GetObject("ico_jira_recent_issues", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_jira_saved_filter {
            get {
                object obj = ResourceManager.GetObject("ico_jira_saved_filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_logworkonissue {
            get {
                object obj = ResourceManager.GetObject("ico_logworkonissue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_pauseissue {
            get {
                object obj = ResourceManager.GetObject("ico_pauseissue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_updateavailable {
            get {
                object obj = ResourceManager.GetObject("ico_updateavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ico_updatenotavailable {
            get {
                object obj = ResourceManager.GetObject("ico_updatenotavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_addattachment {
            get {
                object obj = ResourceManager.GetObject("icon_addattachment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ide_plugin_16 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ide_plugin_16_with_padding {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_16_with_padding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ide_plugin_161 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ide_plugin_300 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_300", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ide_plugin_32 {
            get {
                object obj = ResourceManager.GetObject("ide_plugin_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table class=&quot;summary&quot;&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn labelsummary&quot;&gt;Summary&lt;/td&gt;
        ///&lt;td class=&quot;labelsummary&quot;&gt;
        ///&lt;div onmouseover=&quot;showInline(&apos;summary-edit&apos;);&quot; onmouseout=&quot;hide(&apos;summary-edit&apos;);&quot; &gt;{1}
        ///&lt;div id=&quot;summary-edit&quot; class=&quot;pencil&quot;&gt;&lt;a href=&quot;issueedit:summary&quot;&gt;&lt;img src=&quot;{0}&quot; alt=&quot;Edit&quot; style=&quot;border-style:none;vertical-align:top;&quot;&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Type&lt;/td&gt;&lt;td&gt;&lt;img alt=&quot;&quot; src=&quot;{2}&quot;/&gt;{3}&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Status&lt;/td&gt;&lt;td&gt;&lt;img alt=&quot;&quot; src=&quot;{4}&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string issue_summary_html {
            get {
                return ResourceManager.GetString("issue_summary_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Original Estimate&lt;/td&gt;
        ///&lt;td&gt;&lt;div onmouseover=&quot;showInline(&apos;timetracking-edit&apos;);&quot; onmouseout=&quot;hide(&apos;timetracking-edit&apos;);&quot; &gt;{1}
        ///&lt;div id=&quot;timetracking-edit&quot; class=&quot;pencil&quot;&gt;&lt;a href=&quot;issueedit:timetracking&quot;&gt;
        ///&lt;img src=&quot;{0}&quot; alt=&quot;Edit&quot; style=&quot;border-style:none;vertical-align:top;&quot;&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Remaining Estimate&lt;/td&gt;&lt;td&gt;{2}&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Time Spent&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string issue_summary_original_estimate_editable_html {
            get {
                return ResourceManager.GetString("issue_summary_original_estimate_editable_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Parent Issue&lt;/td&gt;&lt;td&gt;&lt;a href=&quot;parentissue:{0}&quot;&gt;{0}&lt;/a&gt;&lt;/td&gt;
        ///.
        /// </summary>
        internal static string issue_summary_parent_issue_html {
            get {
                return ResourceManager.GetString("issue_summary_parent_issue_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Original Estimate&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Remaining Estimate&lt;/td&gt;
        ///&lt;td&gt;&lt;div onmouseover=&quot;showInline(&apos;timetracking-edit&apos;);&quot; onmouseout=&quot;hide(&apos;timetracking-edit&apos;);&quot; &gt;{2}
        ///&lt;div id=&quot;timetracking-edit&quot; class=&quot;pencil&quot;&gt;&lt;a href=&quot;issueedit:timetracking&quot;&gt;
        ///&lt;img src=&quot;{0}&quot; alt=&quot;Edit&quot; style=&quot;border-style:none;vertical-align:top;&quot;&gt;&lt;/a&gt;&lt;/div&gt;&lt;/div&gt;&lt;/td&gt;&lt;/tr&gt;
        ///
        ///&lt;tr&gt;&lt;td class=&quot;labelcolumn&quot;&gt;Time Spent&lt;/td&gt;&lt;td&gt;{3}&lt;/td&gt;&lt;/tr&gt;
        ///.
        /// </summary>
        internal static string issue_summary_remaining_estimate_editable_html {
            get {
                return ResourceManager.GetString("issue_summary_remaining_estimate_editable_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issues - JIRA.
        /// </summary>
        internal static string IssueDetailsToolWindowTitle {
            get {
                return ResourceManager.GetString("IssueDetailsToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jira_blue_16 {
            get {
                object obj = ResourceManager.GetObject("jira_blue_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap jira_blue_16_with_padding {
            get {
                object obj = ResourceManager.GetObject("jira_blue_16_with_padding", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon jira_blue_161 {
            get {
                object obj = ResourceManager.GetObject("jira_blue_161", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kanban16 {
            get {
                object obj = ResourceManager.GetObject("kanban16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the tab with middle mouse button or click the [x] to close.
        /// </summary>
        internal static string MIDDLE_CLICK_TO_CLOSE {
            get {
                return ResourceManager.GetString("MIDDLE_CLICK_TO_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap new_comment {
            get {
                object obj = ResourceManager.GetObject("new_comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nothing {
            get {
                object obj = ResourceManager.GetObject("nothing", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open_in_ide {
            get {
                object obj = ResourceManager.GetObject("open_in_ide", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pazu {
            get {
                object obj = ResourceManager.GetObject("pazu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon pazu_32 {
            get {
                object obj = ResourceManager.GetObject("pazu_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pin_other {
            get {
                object obj = ResourceManager.GetObject("pin_other", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap projectsettings {
            get {
                object obj = ResourceManager.GetObject("projectsettings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap run_build {
            get {
                object obj = ResourceManager.GetObject("run_build", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scrum16 {
            get {
                object obj = ResourceManager.GetObject("scrum16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search_jira {
            get {
                object obj = ResourceManager.GetObject("search_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] small_throbber {
            get {
                object obj = ResourceManager.GetObject("small_throbber", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_plugin {
            get {
                object obj = ResourceManager.GetObject("status_plugin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap status_plugin1 {
            get {
                object obj = ResourceManager.GetObject("status_plugin1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon status_plugin2 {
            get {
                object obj = ResourceManager.GetObject("status_plugin2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///.summary, .description { 
        ///	font-size:&quot;10pt&quot;;
        ///	font-family:&quot;Arial&quot;; 
        ///}
        ///
        ///.labelcolumn {
        ///	text-align:&quot;left&quot;;
        ///	padding-right:&quot;1em&quot;;
        ///	font-weight:&quot;bold&quot;;
        ///	height:&quot;18px&quot;;
        ///}
        ///
        ///.labelsummary {
        ///	padding-bottom:&quot;18px&quot;;
        ///	height:&quot;18px&quot;;
        ///}
        ///
        ///.linkcategory {
        ///	width:100%;
        ///	background:&quot;lightgrey&quot;;
        ///	padding:&quot;0.5em&quot;;
        ///	font-weight:bold;
        ///}
        ///
        ///.linkdirection {
        ///	padding-left:&quot;2em&quot;;
        ///	padding-top:&quot;0.5em&quot;;
        ///}
        ///
        ///.linkedissues {
        ///	padding-left:&quot;10em&quot;;
        ///	padding-bottom:&quot;1em&quot;;
        ///}
        ///
        ///.issu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string summary_and_description_css {
            get {
                return ResourceManager.GetString("summary_and_description_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_bamboo {
            get {
                object obj = ResourceManager.GetObject("tab_bamboo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_bamboo_grey {
            get {
                object obj = ResourceManager.GetObject("tab_bamboo_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_jira {
            get {
                object obj = ResourceManager.GetObject("tab_jira", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tab_jira_grey {
            get {
                object obj = ResourceManager.GetObject("tab_jira_grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;body&gt;
        ///&lt;div style=&quot;font-family:Arial;font-size:12px;width:100%;height:100%;&quot;&gt;
        ///
        ///&lt;div style=&quot;position:absolute;top:50%;left:50%;margin-left:-16px;margin-top:-16px;&quot;&gt;
        ///&lt;img src=&quot;{0}&quot; alt=&quot;Fetching preview...&quot;&gt;
        ///&lt;/div&gt;
        ///
        ///&lt;/div&gt;
        ///&lt;/body&gt;.
        /// </summary>
        internal static string throbber_html {
            get {
                return ResourceManager.GetString("throbber_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script language=&quot;javascript&quot;&gt;
        ///	function toggle(id, controlid) {
        ///		var el = document.getElementById(id);
        ///		var state = el.style.display;
        ///		if (state == &apos;block&apos;) {
        ///			document.getElementById(id).style.display = &apos;none&apos;;
        ///			document.getElementById(controlid).innerHTML=&quot;expand&quot;;
        ///		} else {
        ///			document.getElementById(id).style.display = &apos;block&apos;;
        ///			document.getElementById(controlid).innerHTML=&quot;collapse&quot;;
        ///		}
        ///	}
        ///	
        ///	function showInline(id) {
        ///		document.getElementById(id).style.display = &apos;inline&apos;;
        ///	} [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string toggler_javascript {
            get {
                return ResourceManager.GetString("toggler_javascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atlassian.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unknown {
            get {
                object obj = ResourceManager.GetObject("unknown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update_unavailable {
            get {
                object obj = ResourceManager.GetObject("update_unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon update_unavailable1 {
            get {
                object obj = ResourceManager.GetObject("update_unavailable1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap view_in_browser {
            get {
                object obj = ResourceManager.GetObject("view_in_browser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VSObject_Class {
            get {
                object obj = ResourceManager.GetObject("VSObject_Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VSObject_Namespace {
            get {
                object obj = ResourceManager.GetObject("VSObject_Namespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
